version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/app
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydb
    command: >
      bash -c "
        uvicorn main:app --host 0.0.0.0 --port 8000
      "

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    healthcheck:
      test: curl -f http://localhost:9200 || exit 1
      interval: 5s
      timeout: 5s
      retries: 12

  indexer:
    build:
      context: .
      dockerfile: Dockerfile.indexer
    depends_on:
      db:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydb
      - ES_URL=http://elasticsearch:9200
    volumes:
      - ./app:/app
      - ./indexer:/indexer

volumes:
  pgdata:
